version: '3.4'
services:
  frontend:
    build: .
    command: npm start
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
      REACT_APP_BACKEND_HOST: "http://localhost:8000"
      REACT_APP_GOOGLE_API_KEY:
    volumes:
      - .:/app

  builder:
    build: .
    command: npm run build
    environment:
      REACT_APP_BACKEND_HOST:
      REACT_APP_GOOGLE_API_KEY:
    volumes:
      - ./build:/app/build
